### ISSUE TITLE
tsc missing

### ISSUE THREAD

**Issue by maziggy** [piotrb/klipper-stats#1]
Looks like a module is missing? Thanks.

Building klipper-stats
[+] Building 4.3s (17/18)
 => [internal] load build definition from Dockerfile                                                                                                                 0.0s
 => => transferring dockerfile: 32B                                                                                                                                  0.0s
 => [internal] load .dockerignore                                                                                                                                    0.0s
 => => transferring context: 34B                                                                                                                                     0.0s
 => [internal] load metadata for docker.io/library/node:18                                                                                                           0.0s
 => CACHED [internal] settings cache mount permissions                                                                                                               0.0s
 => [internal] load build context                                                                                                                                    0.0s
 => => transferring context: 886B                                                                                                                                    0.0s
 => [base 1/4] FROM docker.io/library/node:18                                                                                                                        0.0s
 => CACHED [base 2/4] RUN mkdir -p /app                                                                                                                              0.0s
 => CACHED [base 3/4] RUN chown -R node:node /app                                                                                                                    0.0s
 => CACHED [base 4/4] WORKDIR /app                                                                                                                                   0.0s
 => CACHED [prod 1/4] COPY --chown=node:node .yarn/releases /app/.yarn/releases/                                                                                     0.0s
 => CACHED [prod 2/4] COPY --chown=node:node .yarn/plugins /app/.yarn/plugins/                                                                                       0.0s
 => CACHED [prod 3/4] COPY --chown=node:node package.json .yarnrc.yml yarn.lock /app/                                                                                0.0s
 => CACHED [prod 4/4] RUN --mount=type=cache,target=/opt/.yarn,id=yarn,uid=1000,gid=1000 YARN_CACHE_FOLDER=/opt/.yarn   yarn workspaces focus --all --production     0.0s
 => CACHED [build-deps 1/3] RUN --mount=type=cache,target=/opt/.yarn,id=yarn,uid=1000,gid=1000 YARN_CACHE_FOLDER=/opt/.yarn   yarn workspaces focus --all            0.0s
 => CACHED [build-deps 2/3] COPY --chown=node:node tsconfig.json /app                                                                                                0.0s
 => CACHED [build-deps 3/3] COPY --chown=node:node src /app/src                                                                                                      0.0s
 => ERROR [build 1/1] RUN --mount=type=cache,target=/opt/ts-cache,id=tsc,uid=1000,gid=1000   yarn tsc   --outDir dist                                                4.3s
------
 > [build 1/1] RUN --mount=type=cache,target=/opt/ts-cache,id=tsc,uid=1000,gid=1000   yarn tsc   --outDir dist:
#17 4.226 Usage Error: Couldn't find a script named "tsc".
#17 4.226
#17 4.226 $ yarn run [--inspect] [--inspect-brk] [-T,--top-level] [-B,--binaries-only] <scriptName> ...
------
executor failed running [/bin/sh -c yarn tsc   --outDir dist]: exit code: 1
ERROR: Service 'klipper-stats' failed to build : Build failed

**Comment by maziggy** [comment]
I think it was a problem on my dev host. Working now. Sorry for that.

**Comment by piotrb** [comment]
cool, closing this issue :)
